# Generated by Django 2.2.4 on 2019-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("atracoes", "0001_initial"), ("core", "0002_auto_20190818_2259")]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="atracoes",
            field=models.ManyToManyField(to="atracoes.Atracao"),
        )
    ]
