# Generated by Django 2.2.4 on 2019-08-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("avaliacoes", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="avaliacao", old_name="comentarios", new_name="comentario"
        )
    ]
